### ISSUE TITLE
Does filter support multiple view types as well?

### ISSUE THREAD

**Issue by mochadwi** [gilgoldzweig/Gencycler#3]
https://github.com/gilgoldzweig/Gencycler#filter

cc @gilgoldzweig does your library support filter/query/search when implementing multiple view type adapter?

**Comment by gilgoldzweig** [comment]
Yeah. There shouldn't be a problem due the fact that when you use multiple view-types Gencycler uses the `GencyclerModel` for all the operations, the reason you see your object in the `onBind` method is due to the generated code uses casting as an abstraction.

In addition Gencycler is really flexible, which means you can implement any filter/query/etc.. that you want without jumping through hoops.
